name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build & publish release

    permissions:
      contents: write  # Required to create GitHub Release

    steps:
      # ---------------------------------------------
      # 1. Checkout repository at tagged commit
      # ---------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------------------------------------
      # 2. Setup Node.js and pnpm
      # ---------------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # ---------------------------------------------
      # 3. Install & build
      # ---------------------------------------------
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build extension
        run: pnpm build

      # ---------------------------------------------
      # 4. Package Chrome (and optionally Firefox) builds
      # ---------------------------------------------
      - name: Create ZIP packages
        run: |
          cd dist
          zip -r ../eons-dev-launcher-chrome-${{ github.ref_name }}.zip .
          cd ..
          # Uncomment if you build a Firefox version:
          # cp -r dist dist-firefox
          # cd dist-firefox
          # zip -r ../eons-dev-launcher-firefox-${{ github.ref_name }}.zip .
          # cd ..

      # ---------------------------------------------
      # 5. Create GitHub Release and upload assets
      # ---------------------------------------------
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            eons-dev-launcher-chrome-${{ github.ref_name }}.zip
          generate_release_notes: true
          draft: false
          prerelease: false
